### ISSUE TITLE
Typing during intervals causes unwanted behaviour

### ISSUE THREAD

**Issue by kylerosser** [SquirtleSquadProgramming/ScarkSource#14]
During the story being slowly presented, if you type, later on when the game asks you for input it will have what you typed in the input bar.

This may be problematic if people spam the keyboard whilst waiting for the story to play through as it will be confusing once the game asks for input and already in the box there is "aoiuDGOIWUEDGYFLSIDAUGFLIAWGDSsaw1". 

If there is some way to clear the input bar before using Console.ReadLine() I think we should implement it. If not, this isn't game breaking, but it may confuse some players.

**Comment by derekchai** [comment]
fixed by @BeefStew34

**Comment by kylerosser** [comment]
No, he didn't. He fixed the editing of the console issue, this is entirely different.

**Comment by BeefStew34** [comment]
FIGHT FIGHT FIGHT

**Comment by derekchai** [comment]
ohh

**Comment by BeefStew34** [comment]
So Is This or is This Not Fixed

**Comment by derekchai** [comment]
not fixed
but im on to it

**Comment by derekchai** [comment]
**Closed issue**
Reason: too difficult

**Comment by s-0fia** [comment]
nvm too hard
