### ISSUE TITLE
Speed Setting Request

### ISSUE THREAD

**Issue by kylerosser** [SquirtleSquadProgramming/ScarkSource#17]
I'm always frustrated when I am reading the storyline and even though I have picked out a speed setting, it never seems to match the length of the text, so sometimes I end up waiting a bit or having to skip bits of text because it is too fast.

I would like the speed setting to be a modifier, and that the wait after using the wd() method is in proportion to the length of the text times the modifier I set.

**Comment by derekchai** [comment]
maybe

**Comment by kylerosser** [comment]
Added in latest commit
