### ISSUE TITLE
BUG: variable not working in if statement

### ISSUE THREAD

**Issue by derekchai** [SquirtleSquadProgramming/ScarkSource#22]
**Describe the bug**
See below image for context
In else statement (L85), sets boolean var `tryNoticedBarrel` to true, but in else-if statement (L79), ignores the `tryNoticedBarrel == true` part

![image](https://user-images.githubusercontent.com/18750685/57576225-9554b980-74ae-11e9-8cff-18c1762efc71.png)

**To Reproduce**

*will update later*

**Expected behavior**
Ignores

**Comment by kylerosser** [comment]
I can't see how this doesn't work..

**Comment by derekchai** [comment]
neither lmao

**Comment by BeefStew34** [comment]
idk, maybe change the else if to just an if and see if that works

**Comment by derekchai** [comment]
nope doesnt work ;-;
