### ISSUE TITLE
Trade GUI

### ISSUE THREAD

**Issue by derekchai** [SquirtleSquadProgramming/ScarkSource#25]
**Request**  
Add a trade UI when trading with NPCs as in `BoardShip.cs`. Maybe add a simple list with numbers you can select with the prices alongside.

**Concept**
```
============== TRADE ==============
Here are {NPC_name}'s trades he is offering.

[1] Some item
    Cost: Э 100 // Э could be the currency symbol idk
[2] Another item
    Cost: Э 123

[x] Decline trade
===================================
```

Should be pretty easy to implement

**Comment by derekchai** [comment]
Made concept idea (`Scark/Scark/TradeGUI_Concept.txt`)

**Comment by s-0fia** [comment]
Done!
