### ISSUE TITLE
Error CS0151 "Scark/ast/Other/CASP.cs" L:118

### ISSUE THREAD

**Issue by derekchai** [SquirtleSquadProgramming/ScarkSource#34]
![image](https://user-images.githubusercontent.com/18750685/58141533-cba4ec80-7c97-11e9-83b3-2dff9b199c17.png)
See image (I added `apply.ToString()` in an attempt to fix it but it did not work :/)

@MinnowTheFish this is your crap

**EDIT:** Yes, this is the most current version of Scark (straight off of github), I'm just using Repl.it (downloaded it off of GitHub as a zip and then uploaded it to repl.it) because I am at school UwU

**EDIT:** ScarkSource-master/Scark/Scark/ast/Other/CASP.cs(118,17): error CS0151: A switch expression of type `dynamic' cannot be converted to an integral type, bool, char, string, enum or nullable type

**Comment by s-0fia** [comment]
Will fix by changing it from `Console.ReadLine()` => `Console.ReadKey()` and removing the string processing (I will also apply this to all other inputs so give me a while)
