### ISSUE TITLE
Add contents to the barrel

### ISSUE THREAD

**Issue by s-0fia** [SquirtleSquadProgramming/ScarkSource#39]
![image](https://user-images.githubusercontent.com/39723774/62409569-a0426480-b62d-11e9-8e52-092e5a5d4665.png)
We should add something to the barrel... Maybe Ethryl?
`./ast/narsk/TowardsMedallion.cs:223-230`

**Comment by kylerosser** [comment]
I think it should be a weapon once we get an inventory sorted out

**Comment by s-0fia** [comment]
> I think it should be a weapon once we get an inventory sorted out

The inventory is sorted out (I **_might_** make a guide on how to add an weapon/item)
